# Generated by Django 5.2.15 on 2026-06-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=255, unique=True)),
                ('bank_code', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('join_way', models.TextField(blank=True)),
                ('target_user', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_trm', models.IntegerField()),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('max_interest_rate', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.financialproduct')),
            ],
        ),
    ]
