# Generated by Django 5.2.14 on 2026-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproduct',
            name='special_condition',
            field=models.TextField(blank=True, help_text='최고금리 우대 조건'),
        ),
    ]
