# Generated by Django 5.2.4 on 2026-06-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
