# Generated by Django 5.2.14 on 2026-06-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stockprice_recorded_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('stock', 'recorded_at')},
        ),
    ]
