# Generated by Django 5.2.14 on 2026-06-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='거주 주소 (인근 은행 기반 추천에 사용)', max_length=255),
        ),
    ]
