# Generated by Django 5.2.14 on 2026-06-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('card_name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='cardbenefit',
            unique_together={('card', 'benefit_category', 'benefit_detail')},
        ),
    ]
