# Generated by Django 5.2.14 on 2026-06-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('financial_type', models.CharField(blank=True, max_length=50)),
                ('economy_summary', models.JSONField(default=list)),
                ('actions', models.JSONField(default=list)),
                ('tip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'financial_type')},
            },
        ),
    ]
