# Generated by Django 5.2.14 on 2026-06-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentproduct',
            name='viewed_at',
            field=models.DateTimeField(),
        ),
    ]
